### ISSUE TITLE
CGContext errors

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/edd-ios#45]
On build, I'm getting `CGContext` errors:
```objective-c
Aug 25 19:43:33  EDDSalesTracker[537] <Error>: CGContextSaveGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Aug 25 19:43:33  EDDSalesTracker[537] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Aug 25 19:43:33  EDDSalesTracker[537] <Error>: CGContextRestoreGState: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
```

**Comment by DennisXiaoDing** [comment]
https://forums.developer.apple.com/message/38469#38469

**Comment by sunnyratilal** [comment]
This bug is to do with the current version of the app (in the App Store) incorrectly passing control of `UIViewControllerBasedStatusBarAppearance` property to view controllers.  New version of the app doesn't follow this implementation of delegating status bar appearance to the presented view controller i.e. error gone.
